config/routes.rb
TcOnRails::Application.routes.draw do
  
  get "/"                   => "games#welcome",      as: :root
  get "/rules"              => "games#rules",        as: :rules
  get "/about"              => "games#about",        as: :about
  post "/lets_play"         => "games#lets_play",    as: :lets_play
  get "/game_on/:game_id/:evaluation/:current_player"   => "games#game_on", as: :game_on
  post "/player_guess/:game_id"      => "games#player_guess", as: :player_guess
  get "/route_1_page"       => "games#route_1"  
  get "/route_2_page"       => "games#route_2"

end

app/models/game.rb
class Game < ActiveRecord::Base
  
	attr_accessible :consecutive_correct_guesses, :direction, :last_correct_guesser


	has_many :cards
	has_many :players

	def self.track_consecutive_correct_guesses(game_id, guess_evaluation, current_player_number)
		game = Game.find(game_id)
		if guess_evaluation == "correct"
			game.consecutive_correct_guesses += 1
			game.last_correct_guesser = current_player_number
		elsif guess_evaluation == "wrong" || guess_evaluation == "sweep"
			game.consecutive_correct_guesses = 0
		else
		end
		game.save!
	end
  
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController


	def lets_play #(Post from welcome page)
		game = Game.new
		game.consecutive_correct_guesses = 0
		game.direction = "ascending"
		game.save!
		Player.create_players(params[:player_name], game)
		Card.create_deck(game.id)
		Card.dealer_flips_card(game.id)		
		evaluation = "none"
		redirect_to "/game_on/#{game.id}/#{evaluation}/#{Player.where(game_id: game.id).first.name}"

	end

	def game_on
		
		game_id = params[:game_id]
		game_cards = Card.where(game_id: game_id)
		@players_in_order = Player.where(game_id: game_id).order(:number)
		@player =  Player.where(game_id: game_id).where(name: params[:current_player]).first #Player.where(game_id: game_id).where(current_player: 1).first || @players_in_order.first
		@card_in_play = game_cards.where(status: "card_in_play").first.name
		@cards_remaining_in_deck = game_cards.where(status: "not_in_play").count
		@cards_in_the_pot = Card.show_cards_in_the_pot(game_id)
		@evaluation = params[:evaluation]
		@consecutive_correct_guesses = Game.find(game_id).consecutive_correct_guesses
		#####showing cards in deck for feature testing purposes only
		deck_array = []
		game_cards.where(status: "not_in_play").order(:card_order).limit(10).each { |card| deck_array << card.name } 
		@deck_array = deck_array
		#####

		render(:game_on)
	end

	def player_guess #(Post from game_on page)
		game_id = params[:game_id]
		current_player_number = params[:number]
		if params[:end_game]
			redirect_to root_path

		else
			if params[:sweep]
				guess_evaluation = params[:sweep]
				card_in_play = 'n/a'
				flipped_card = 'n/a'
			else
				guess = params[:higher] || params[:lower] 
				card_in_play = Card.where(game_id: game_id).where(status: "card_in_play").first.name
				flipped_card = Card.dealer_flips_card(game_id)

				guess_evaluation = Card.evaluate_guess(game_id, guess, card_in_play, flipped_card)
				
			end
			Game.track_consecutive_correct_guesses(game_id, guess_evaluation, current_player_number)
			Card.award_cards_in_the_pot(game_id, current_player_number, guess_evaluation)
			next_current_player = Player.determine_the_next_player(game_id, current_player_number, guess_evaluation)
			
			Card.determine_the_card_in_play_for_next_hand(game_id, guess_evaluation, card_in_play, flipped_card)
			redirect_to "/game_on/#{game_id}/#{guess_evaluation}/#{next_current_player}"
		end
	end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/about.html.erb
<h1>About</h1>

<p>"Tuff Cookies was........."</p><br>

<%= link_to "Back", root_path %>

app/views/games/game_on.html.erb
<h1> Tuff Cookies - Game On! </h1>

<%= form_tag player_guess_path(@player.game_id) do %>

<p><b>Current Player: <%= @player.name%> </b></p> 

<p>Cards in Deck: <%= @cards_remaining_in_deck %></p>
<p><b>Card in Play: <%=@card_in_play%> </b></p>
<p>Cards in the Pot: <%=@cards_in_the_pot.count%> <%=@cards_in_the_pot%> </p>
<p>Consecutive Correct Guesses: <%=@consecutive_correct_guesses%></p>
<p><b>Last Guess Was: <%=@evaluation%></b></p>

<% if @card_in_play.to_i != 0 %>
	<%= button_tag "Higher", name: "higher", value: "higher" %>
	<%= button_tag "Lower", name: "lower", value: "lower" %>
	<%if @consecutive_correct_guesses >= 3 && Game.find(@player.game_id).last_correct_guesser == @player.number%>
		<%= button_tag "Sweep", name: "sweep", value: "sweep" %>
	<%end%>
<%else%>
<%= button_tag "Next Card", name: "next_card", value: "next_card"%>
<%end%>
<%= button_tag "End Game", name: "end_game", value: "end_game"%>

<br><br>
######<br>
Cheat for End User Testing  <br>
Cards in Deck: <%=@deck_array%><br>
Player Order: <%=hidden_field_tag "number", @player.number %><br> 
Game ID: <%= @player.game_id%><br>
Game Direction: <%=Game.find(@player.game_id).direction%><br>
######
<%end%> 

<h3><b>Player Order and Score </b></h3>  
<% for each in @players_in_order %>
<%=each.name%> - <%=Card.where(game_id: each.game_id).where(owner: each.name).count%>
<br>
<%end%>
</p>	

app/views/games/rules.html.erb
<h1>Rules</h1>

<p>"Rules......"</p><br>

<%= link_to "Back", root_path %>

app/views/games/welcome.html.erb
<h1>Welcome to Tuff Cookies! </h1>

<p>Enter Your Name to Begin Playing: </p>
<%= form_tag "lets_play" do %>
	<%= text_field_tag "player_name" %>
	<%= button_tag "Let's Play!"%>
<%end%>

<br><br><br><br>

<%= link_to "Rules", rules_path %>

<%= link_to "About", about_path %>